# Generated by Django 5.0.6 on 2026-07-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=10),
        ),
        migrations.CreateModel(
            name='FlaggedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_reason', models.CharField(choices=[('radius', 'Out of Radius'), ('suspicious', 'Suspicious Activity / Spoofing')], default='radius', max_length=20)),
                ('device_info', models.CharField(default='Mobile Device (Verified)', max_length=100)),
                ('integrity_status', models.CharField(blank=True, help_text='e.g., Low / Spoofing Alert', max_length=100, null=True)),
                ('reported_location_name', models.CharField(blank=True, help_text='e.g., Library Wing', max_length=100, null=True)),
                ('detected_velocity', models.CharField(blank=True, help_text='e.g., 120 km/h (Invalid)', max_length=50, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_detail', to='geo.attendancerecord')),
            ],
            options={
                'verbose_name_plural': 'Flagged Entries',
                'ordering': ['-attendance_record__timestamp'],
            },
        ),
    ]
