# Generated by Django 5.0.6 on 2026-07-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_attendancerecord_status_flaggedentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
